name: C/C++ CI (Ubuntu)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake .
    - name: msbuild
      run: msbuild /home/runner/work/WindowsXPKg/WindowsXPKg
