name: C/C++ CI (Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake ./
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: idk
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/WindowsXPKg/WindowsXPKg
        # The desired behavior if no files are found using the provided path.
