name: C/C++ CI (Linux)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install OpenSSL
      run: wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.1.1f-1ubuntu2.16_amd64.deb; wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2.16_amd64.deb; wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb; sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb; sudo dpkg -i libssl-dev_1.1.1f-1ubuntu2.16_amd64.deb; sudo dpkg -i openssl_1.1.1f-1ubuntu2.16_amd64.deb
    - name: Build
      uses: threeal/cmake-action@latest
    - name: Move files to correct directory
      # stop abbreviating things "cp"
      run: mkdir /home/runner/work/WindowsXPKg/WindowsXPKg/build/actions_upload; cp /home/runner/work/WindowsXPKg/WindowsXPKg/build/xpkey /home/runner/work/WindowsXPKg/WindowsXPKg/build/actions_upload/xpkey; cp /home/runner/work/WindowsXPKg/WindowsXPKg/build/keys.json /home/runner/work/WindowsXPKg/WindowsXPKg/build/actions_upload/keys.json;
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build
        path: /home/runner/work/WindowsXPKg/WindowsXPKg/build/actions_upload
