name: C/C++ CI (Linux)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure and build this project
      uses: threeal/cmake-action@latest
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build
        path: /home/runner/work/WindowsXPKg/WindowsXPKg/
