name: C/C++ CI (Linux)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3\
    - name: Install OpenSSL
      run: wget https://www.openssl.org/source/openssl-1.1.1b.tar.gz; sudo mkdir /opt/openssl; sudo tar xfvz ./openssl-1.1.1b.tar.gz --directory /opt/openssl; export LD_LIBRARY_PATH=/opt/openssl/lib; cd /opt/openssl/openssl-1.1.1b; sudo ./config --prefix=/opt/openssl --openssldir=/opt/openssl/ssl; sudo make; sudo make test; sudo make install; cd /home/runner/work/WindowsXPKg/WindowsXPKg
    - name: Build
      uses: threeal/cmake-action@latest
    - name: Move files to correct directory
      # stop abbreviating things "cp"
      run: mkdir /home/runner/work/WindowsXPKg/WindowsXPKg/build/actions_upload; cp /home/runner/work/WindowsXPKg/WindowsXPKg/build/xpkey /home/runner/work/WindowsXPKg/WindowsXPKg/build/actions_upload/xpkey; cp /home/runner/work/WindowsXPKg/WindowsXPKg/build/keys.json /home/runner/work/WindowsXPKg/WindowsXPKg/build/actions_upload/keys.json;
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build
        path: /home/runner/work/WindowsXPKg/WindowsXPKg/build/actions_upload
