name: C/C++ CI (Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build WindowsXPKg
        run: |
          cd build
          cmake ../
          msbuild ALL_BUILD.vcxproj /P:Configuration=Release
        
      - name: Copy files and clean up output directory
        run: |
          del "build/Release/*.lib"
          copy "keys.json" "build/Release/keys.json"

      - name: Test WindowsXPKg 
        run: | # source: https://www.youtube.com/watch?v=O9xfQNAHsJE
          build/Release/xpkey.exe
          build/Release/xpkey.exe -i 319941-863600-898123-625494-221595-379341-028684-143716-854300
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: WindowsXPKg-Win64
          path: build/Release
